version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
      time: '09:00'
    target-branch: dev
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: daily
    target-branch: dev
    open-pull-requests-limit: 1